name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : codeasa
      USER_EMAIL  : code@asachoi.com      
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      run: npm i
    
    - name: Build project
      run: yarn build
    
    - name: Deploy project
      run: |
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        yarn deploy
